//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSP4VS.ConfigNode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KSP4VS.ConfigNode.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only have one of the following: BEFORE, AFTER, FIRST, or FINAL..
        /// </summary>
        internal static string CN001 {
            get {
                return ResourceManager.GetString("CN001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only have one FOR declaration..
        /// </summary>
        internal static string CN002 {
            get {
                return ResourceManager.GetString("CN002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only have BEFORE, AFTER, FIRST, FINAL, or FOR on a top level node..
        /// </summary>
        internal static string CN003 {
            get {
                return ResourceManager.GetString("CN003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched &quot;{&quot;.
        /// </summary>
        internal static string configNode_noClose {
            get {
                return ResourceManager.GetString("configNode_noClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid charaters in ModuleManager selector.
        /// </summary>
        internal static string MMnamePattern_InvalidChar {
            get {
                return ResourceManager.GetString("MMnamePattern_InvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in name.
        /// </summary>
        internal static string name_InvalidChar {
            get {
                return ResourceManager.GetString("name_InvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &quot;=&quot; on value entry.
        /// </summary>
        internal static string nameValuePair_noEq {
            get {
                return ResourceManager.GetString("nameValuePair_noEq", resourceCulture);
            }
        }
    }
}
